### ISSUE TITLE
Proposal and additions

### ISSUE THREAD

**Issue by merkushev88** [data-burst/airflow-git-sync#22]
Hello! I really liked your solution to the problem. But I'd like to ask:

Is it possible to use two/three gitlab repositories in one Docker Compose file?
Is it possible to ignore unnecessary files from the repository, for example readme.md?

**Comment by mostafaghadimi** [comment]
Hello @merkushev88, I hope you are doing well.

1. Contrary to your assumption, this repository is designed with the idea that all DAGs are housed within a single repository. This approach facilitates the implementation of a GitOps solution.
2. As for your second point, the implementation differs slightly. We assume that all DAGs are located within a single directory (which can be nested). You can then utilize the `SUBFOLDER_PATH` as outlined in our documentation.

I hope this clarifies your queries. Please feel free to reach out if you have any further questions or concerns.

**Comment by merkushev88** [comment]
thanks for your answer!
